---
- name: Install Apache
  apt: name={{ item }} state=present
  with_items:
    - apache2

- name: Put www-data user in sslcerts group
  user: name=www-data append=yes groups=ssl-cert

- name: Prepare httpd for Let's Encrypt client
  copy: src=letsencrypt.conf dest=/etc/apache2/conf-available/letsencrypt.conf
  notify: restart apache2

- name: Enable letsencrypt.conf
  file:
    src: /etc/apache2/conf-available/letsencrypt.conf
    dest: /etc/apache2/conf-enabled/letsencrypt.conf
    state: link
  notify: restart apache2

- name: Configure vhost
  template: src=ox.conf dest=/etc/apache2/sites-available/ox.conf
  notify: restart apache2

- name: Enable ox vhost
  file:
    src: /etc/apache2/sites-available/ox.conf
    dest: /etc/apache2/sites-enabled/ox.conf
    state: link
  notify: restart apache2

- name: Enable apache2 modules
  command: a2enmod ssl headers expires rewrite
  notify: restart apache2
  
