---
- name: Install Postfix
  apt: name={{ item }} state=present
  with_items:
    - postfix

- name: Add submission instance
  blockinfile: 
    dest: /etc/postfix/master.cf
    block: |
      submission inet n       -       -       -       -       smtpd
        -o syslog_name=postfix/submission
        -o smtpd_tls_wrappermode=no
        -o smtpd_tls_security_level=encrypt
        -o smtpd_sasl_auth_enable=yes
        -o smtpd_recipient_restrictions=permit_mynetworks,permit_sasl_authenticated,reject
        -o milter_macro_daemon_name=ORIGINATING
        -o smtpd_sasl_type=dovecot
        -o smtpd_sasl_path=private/auth

- name: Configure main.cf
  template: src=main.cf dest=/etc/postfix/main.cf
  notify: restart postfix

- name: Configure MySQL connections 
  template: src={{ item }} dest=/etc/postfix/{{ item }}
  with_items:
    - mysql-virtual-mailbox-domains.cf
    - mysql-virtual-mailbox-maps.cf
    - mysql-virtual-alias-maps.cf
  notify: restart postfix

- name: Start and enable Postfix
  service: name=postfix enabled=yes state=started
