---
- name: Download Dehydrated Let's Encrypt client
  get_url: url=https://github.com/lukas2511/dehydrated/archive/v{{ letsencrypt_version }}.tar.gz dest=/usr/src/

- name: Extract Dehydrated Let's Encrypt client
  unarchive: src=/usr/src/dehydrated-{{ letsencrypt_version }}.tar.gz dest=/usr/src copy=no creates=/usr/src/dehydrated-{{ letsencrypt_version }}

- name: Create directories
  file: path={{ item }} state=directory mode=0755
  with_items:
    - /etc/letsencrypt
    - /etc/letsencrypt/.acme-challenges
    - /etc/letsencrypt/hooks.d
    - /etc/letsencrypt/hooks.d/deploy_challenge
    - /etc/letsencrypt/hooks.d/clean_challenge
    - /etc/letsencrypt/hooks.d/deploy_cert
    - /etc/letsencrypt/hooks.d/unchanged_cert
    - /etc/letsencrypt/hooks.d/invalid_challenge
    - /etc/letsencrypt/hooks.d/request_failure
    - /etc/letsencrypt/hooks.d/exit_hook

- name: Create directory /etc/letsencrypt/certs
  file: path=/etc/letsencrypt/certs state=directory mode=0750 group=sslcerts owner=root

- name: Link docs directory to /etc/letsencrypt/docs
  file: src=/usr/src/dehydrated-{{ letsencrypt_version }} dest=/etc/letsencrypt/docs state=link

- name: Link /etc/dehydrated to /etc/letsencrypt
  file: src=/etc/letsencrypt dest=/etc/dehydrated state=link

- name: Copy dehydrated binary to /usr/sbin/letsencrypt
  copy: remote_src=yes src=/usr/src/dehydrated-{{ letsencrypt_version }}/dehydrated dest=/usr/sbin/dehydrated mode=0755

- name: Create file /etc/letsencrypt/domains.txt
  copy: remote_src=yes src=/dev/null dest=/etc/letsencrypt/domains.txt mode=0640 force=no

- name: Set daily cron
  copy: src=cron.daily dest=/etc/cron.daily/letsencrypt mode=0755

- name: Set Dehydrated config file
  copy: src=config dest=/etc/letsencrypt/config mode=0640

- name: Set hooks.sh script
  copy: src=hooks.sh dest=/etc/letsencrypt/hooks.sh mode=0750 owner=root group=root

- name: Add FQDN to domains.txt
  lineinfile: dest=/etc/letsencrypt/domains.txt line={{ fqdn }}

- name: Register client and accept terms
  command: /usr/sbin/dehydrated --accept-terms --register creates=/etc/letsencrypt/accounts
